
[project]
name = "screenplain"
version = "0.11.1"
description = "Convert text file to viewable screenplay."
readme = { file = "README.md", content-type = "text/markdown" }
authors = [{ name = "Martin Vilcans", email = "screenplain@librador.com" }]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = []
license = { file = "LICENSE.txt" }
requires-python = ">=3.8"

[project.urls]
Homepage = "http://www.screenplain.com/"
"Web Page" = "http://www.screenplain.com/"
Source = "https://github.com/vilcans/screenplain"

[project.optional-dependencies]
PDF = ["reportlab"]

[project.scripts]
screenplain = "screenplain.main:cli"

[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"

[[tool.hatch.envs.hatch-test.matrix]]
python = [
    "3.13", 
    "3.12", 
    "3.11", 
    "3.10", 
    "3.9", 
    "3.8",
]

[tool.hatch.envs.hatch-static-analysis]
config-path = "none"
dependencies = ["pydocstyle"]
python = "3.13"

[tool.hatch.envs.hatch-static-analysis.scripts]
format-check = ""
format-fix = ""
lint-check = "pycodestyle --ignore=E402,W504 screenplain tests {args}"
lint-fix = "lint-check"

[tool.pytest.ini_options]
addopts = "--doctest-modules -W error"